site_name: sonic-operator

docs_dir: docs

theme:
  name: material

plugins:
  - search

nav:
  - Documentation: README.md
  - Concepts:
      - Overview: concepts/overview.md
      - Resources: concepts/resources.md
  - Usage:
      - Getting started: usage/getting-started.md
      - Provisioning: usage/provisioning.md
      - Agent: usage/agent.md
  - API reference: api-reference/api.md
  - Development:
      - Dev workflow: development/dev-workflow.md
      - REUSE: development/reuse.md
