# This rule is not used by the project sonic-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to sonic.networking.metal.ironcore.dev resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: sonic-operator
    app.kubernetes.io/managed-by: kustomize
  name: switchinterface-viewer-role
rules:
- apiGroups:
  - sonic.networking.metal.ironcore.dev
  resources:
  - switchinterfaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sonic.networking.metal.ironcore.dev
  resources:
  - switchinterfaces/status
  verbs:
  - get
