# This rule is not used by the project switch-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over networking.networking.metal.ironcore.dev.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: switch-operator
    app.kubernetes.io/managed-by: kustomize
  name: switch-admin-role
rules:
- apiGroups:
  - networking.metal.ironcore.dev
  resources:
  - switches
  verbs:
  - '*'
- apiGroups:
  - networking.metal.ironcore.dev
  resources:
  - switches/status
  verbs:
  - get
