# This rule is not used by the project sonic-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over sonic.networking.metal.ironcore.dev.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: sonic-operator
    app.kubernetes.io/managed-by: kustomize
  name: switchinterface-admin-role
rules:
- apiGroups:
  - sonic.networking.metal.ironcore.dev
  resources:
  - switchinterfaces
  verbs:
  - '*'
- apiGroups:
  - sonic.networking.metal.ironcore.dev
  resources:
  - switchinterfaces/status
  verbs:
  - get
