## Append samples of your project ##
resources:
- networking_v1alpha1_switch.yaml
- networking_v1alpha1_switchinterface.yaml
- networking_v1alpha1_switchcredentials.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
