apiVersion: sonic.networking.metal.ironcore.dev/v1alpha1
kind: SwitchCredentials
metadata:
  labels:
    app.kubernetes.io/name: sonic-operator
    app.kubernetes.io/managed-by: kustomize
  name: switchcredentials-sample
stringData:
  username: admin
  password: supersecret
