apiVersion: networking.networking.metal.ironcore.dev/v1alpha1
kind: SwitchCredentials
metadata:
  labels:
    app.kubernetes.io/name: switch-operator
    app.kubernetes.io/managed-by: kustomize
  name: switchcredentials-sample
spec:
  # TODO(user): Add fields here
