apiVersion: networking.metal.ironcore.dev/v1alpha1
kind: Switch
metadata:
  labels:
    app.kubernetes.io/name: switch-operator
    app.kubernetes.io/managed-by: kustomize
  name: switch-sample
spec:
  # TODO(user): Add fields here
