apiVersion: sonic.networking.metal.ironcore.dev/v1alpha1
kind: SwitchInterface
metadata:
  labels:
    app.kubernetes.io/name: sonic-operator
    app.kubernetes.io/managed-by: kustomize
  name: switchinterface-sample
spec:
  handle: Ethernet0
  switchRef:
    name: spine-1
  adminState: Up
